#! /bin/sh

for size in 16 32 48 64 144 196 256 512 1024; do
  rsvg-convert --format png --width $size --height $size icon.svg > icon-$size.png
done
convert -bordercolor white -border 0 \
  \( icon-16.png \) \
  \( icon-32.png \) \
  \( icon-48.png \) \
  \( icon-64.png \) \
  \( icon-144.png \) \
  \( icon-196.png \) \
  \( icon-512.png \) \
  \( icon-1024.png \) \
  icon.ico
